routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/getting-started', 'HomeController@start');
Route::post('/start', 'HomeController@starting');

Auth::routes();

Route::resource('narudžbenice', 'NarudzbenicaController')->middleware('auth');
Route::resource('fakture', 'FakturaController')->middleware('auth');
Route::resource('otpremnice', 'OtpremnicaController')->middleware('auth');
Route::resource('roba', 'RobaController')->middleware('auth');
Route::resource('grupa-robe', 'GrupaRobeController')->middleware('auth');
Route::resource('pdv', 'PdvController')->middleware('auth');
Route::resource('cenovnici', 'CenovnikController')->middleware('auth');
Route::put('cenovnici/aktivan/{cenovnik}', 'CenovnikController@toggleActive')->middleware('auth')->name('cenovnici.active');

Route::get('faktura/download/{faktura}', 'FakturaController@download')->name('faktura.download');

app/Pdv.php
<?php

namespace App;

use App\PdvStopa;
use Illuminate\Database\Eloquent\Model;

class Pdv extends Model
{
    protected $guarded = [];
    
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'pdv';

    public function stope()
    {
        return $this->hasMany(PdvStopa::class);
    }

    public function aktivnaStopa() 
    {
        return $this->hasOne(PdvStopa::class)
                    ->where('aktivan', '1');
    }
}

app/Http/Controllers/PdvController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PdvRequest;
use App\Pdv;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class PdvController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            return DataTables::eloquent(
                    Pdv::query()
                        ->with('aktivnaStopa')
                )->addColumn('action', function ($pdv) {
                   return view('pdv.datatable-action', compact('pdv'));
               })->make();
        }

        return view('pdv.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pdv.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PdvRequest $request)
    {
        $pdv = Pdv::create($request->only('naziv'));

        $pdv->stope()
            ->create($request->only('procenat', 'vazi_do'));

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pdv  $pdv
     * @return \Illuminate\Http\Response
     */
    public function show(Pdv $pdv)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pdv  $pdv
     * @return \Illuminate\Http\Response
     */
    public function edit(Pdv $pdv)
    {
        return view('pdv.edit')->with(
            'pdv', $pdv
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pdv  $pdv
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pdv $pdv)
    {
        $pdv->stope()
            ->where('aktivan', 1)
            ->update(['aktivan' => 0]);
        
        $pdv->stope()
            ->create($request->all());

        return redirect()->route('pdv.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pdv  $pdv
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pdv $pdv)
    {
        //
    }
}

resources/views/pdv/create.blade.php
@extends('layouts.master')
@section('title', __('Novi pdv'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Novi pdv') }}</h3>

            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('Novi pdv') }}</h5>
                                    <form action="{{ route('pdv.store') }}" method="POST">
                                        @csrf
                                        <div class="form-group row">
                                            <label for="naziv-input" class="col-sm-3 form-control-label">{{ __('Naziv') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="naziv"
                                                    class="form-control {{ $errors->has('naziv') ? 'is-invalid' : '' }}"
                                                    id="naziv-input"
                                                    placeholder="{{ __('Unesite naziv') }}"
                                                    value="{{ old('naziv') }}"
                                                >
                                                @if($errors->has('naziv'))
                                                    <small class="text-danger">{{ $errors->first('naziv') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="procenat-input" class="col-sm-3 form-control-label">{{ __('Procenat') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="number"
                                                    name="procenat"
                                                    class="form-control {{ $errors->has('procenat') ? 'is-invalid' : '' }}"
                                                    id="procenat-input"
                                                    placeholder="{{ __('Unesite procenat') }}"
                                                    value="{{ old('procenat') }}"
                                                    step=".01"
                                                >
                                                @if($errors->has('procenat'))
                                                    <small class="text-danger">{{ $errors->first('procenat') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="vazi-do-input" class="col-sm-3 form-control-label">{{ __('Važi do') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="datetime-local"
                                                    min="2019-01-01T00:00" 
                                                    max="2030-01-14T00:00"
                                                    step="1"
                                                    name="vazi_do"
                                                    class="form-control {{ $errors->has('vazi_do') ? 'is-invalid' : '' }}"
                                                    id="vazi-do-input"
                                                    placeholder="{{ __('Unesite datum važenja') }}"
                                                    value="{{ old('vazi_do') }}"
                                                >
                                                @if($errors->has('vazi_do'))
                                                    <small class="text-danger">{{ $errors->first('vazi_do') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <button class="float-right btn btn-primary">{{ __('Submit') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="text/javascript">
$(document).ready(function() {

});
</script>
@endsection

resources/views/pdv/datatable-action.blade.php
<div class="ks-controls">
    <a href="{{ route('pdv.edit', ['pdv' => $pdv]) }}" target="_blank">
        <button type="button" class="btn btn-primary ks-light ks-no-text" style="line-height: 38px;">
            <span class="la la-plus ks-icon"></span>
        </button>
    </a>
</div>

resources/views/pdv/edit.blade.php
@extends('layouts.master')
@section('title', __('Izmenite pdv stopu'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Izmenite pdv stopu') }}</h3>

            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('Izmenite pdv stopu') }}</h5>
                                    <form action="{{ route('pdv.update', $pdv) }}" method="POST">
                                        @method('PUT')
                                        @csrf
                                        <div class="form-group row">
                                            <label for="procenat-input" class="col-sm-3 form-control-label">{{ __('Procenat') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="number"
                                                    name="procenat"
                                                    class="form-control {{ $errors->has('procenat') ? 'is-invalid' : '' }}"
                                                    id="procenat-input"
                                                    placeholder="{{ __('Unesite procenat') }}"
                                                    value="{{ old('procenat', $pdv->aktivnaStopa->procenat) }}"
                                                    step=".01"
                                                >
                                                @if($errors->has('procenat'))
                                                    <small class="text-danger">{{ $errors->first('procenat') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="vazi-do-input" class="col-sm-3 form-control-label">{{ __('Važi do') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="datetime-local"
                                                    min="2019-01-01T00:00" 
                                                    max="2030-01-14T00:00"
                                                    step="1"
                                                    name="vazi_do"
                                                    class="form-control {{ $errors->has('vazi_do') ? 'is-invalid' : '' }}"
                                                    id="vazi-do-input"
                                                    placeholder="{{ __('Unesite datum važenja') }}"
                                                    value="{{ old('vazi_do') }}"
                                                >
                                                @if($errors->has('vazi_do'))
                                                    <small class="text-danger">{{ $errors->first('vazi_do') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <button class="float-right btn btn-primary">{{ __('Submit') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="text/javascript">
$(document).ready(function() {

});
</script>
@endsection

resources/views/pdv/index.blade.php
@extends('layouts.master')
@section('title', __('PDV'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('PDV') }}</h3>
            
            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-body-wrap-container">
                <div class="ks-full-table">
                    <div class="ks-full-table-header">
                        <h4 class="ks-full-table-name">{{ __('PDV')}}</h4>
                        <div class="ks-controls">
                            <a href="{{ route('pdv.create') }}">
                                <button class="btn btn-primary">{{ __('Napravite novi pdv')}}</button>
                            </a>
                        </div>
                    </div>
                    <table id="pdv-table" class="table ks-table-info dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th width="1">ID </th>
                                <th>{{ __('Naziv') }}</th>
                                <th>{{ __('Trenutna stopa') }}</th>
                                <th>{{ __('Akcija') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('external-js')
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/select2/js/select2.min.js') }}"></script>
<script type="application/javascript">var DatatablesDataSourceAjaxServer = {
    init: function () {
        $("#pdv-table").DataTable({
            responsive: true, 
            searchDelay: 500, 
            processing: true, 
            serverSide: true, 
            ajax:"/pdv", 
            columns: [
                { data: "id" }, 
                { data: "naziv" },
                { data: "aktivna_stopa.procenat" },
                { data: "action" }
            ]
        })
    }
};

jQuery(document).ready(function () {
    DatatablesDataSourceAjaxServer.init();

    $('body').delegate('.delete-group', 'click', function (e) {
        e.preventDefault();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var id = $(this).data('id');
        var name = $(this).data('name');
        var table = $("#groups-table").DataTable();
        var tr = $(this).parents('tr');

        $.confirm({
            title: 'Pažnja!',
            content: 'Da li želite da obrišete ' + name + '?',
            type: 'danger',
            buttons: {
                confirm: {
                    text: 'OK',
                    btnClass: 'btn-danger',
                    action: function () {
                        $.ajax({
                            url: '/pdv/' + id,
                            type: 'DELETE',
                        })
                        .done(function(data) {
                            table.row(tr).remove().draw();
                            ajaxNotify(data);
                        })
                        .fail(function() {
                            alert('Dogodila se greška');
                        });
                    }
                },
                cancel: function () {

                }
            }
        });
    });
});

</script>
@endsection