routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/getting-started', 'HomeController@start');
Route::post('/start', 'HomeController@starting');

Auth::routes();

Route::resource('narudžbenice', 'NarudzbenicaController')->middleware('auth');
Route::resource('fakture', 'FakturaController')->middleware('auth');
Route::resource('otpremnice', 'OtpremnicaController')->middleware('auth');
Route::resource('roba', 'RobaController')->middleware('auth');
Route::resource('grupa-robe', 'GrupaRobeController')->middleware('auth');
Route::resource('pdv', 'PdvController')->middleware('auth');
Route::resource('cenovnici', 'CenovnikController')->middleware('auth');
Route::put('cenovnici/aktivan/{cenovnik}', 'CenovnikController@toggleActive')->middleware('auth')->name('cenovnici.active');

Route::get('faktura/download/{faktura}', 'FakturaController@download')->name('faktura.download');

app/GrupaRobe.php
<?php

namespace App;

use App\Pdv;
use App\Preduzece;
use App\Roba;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class GrupaRobe extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'grupe_robe';

    public function pdv()
    {
        return $this->belongsTo(Pdv::class);
    }

    public function preduzece()
    {
        return $this->belongsTo(Preduzece::class);
    }

    public function roba()
    {
        return $this->hasMany(Roba::class, 'grupa_robe_id');
    }
}

app/Http/Controllers/GrupaRobeController.php
<?php

namespace App\Http\Controllers;

use App\GrupaRobe;
use App\Http\Requests\GrupaRobeRequest;
use App\Pdv;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class GrupaRobeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            return DataTables::eloquent(
                    GrupaRobe::query()
                        ->with('pdv', 'pdv.aktivnaStopa')
                )->addColumn('action', function ($grupaRobe) {
                   return view('grupa_robe.datatable-action', compact('grupaRobe'));
               })->make();
        }

        return view('grupa_robe.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('grupa_robe.create')->with([
            'pdvs' => Pdv::with('aktivnaStopa')->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GrupaRobeRequest $request)
    {
        GrupaRobe::create($request->all());

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\GrupaRobe  $grupaRobe
     * @return \Illuminate\Http\Response
     */
    public function show(GrupaRobe $grupaRobe)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\GrupaRobe  $grupaRobe
     * @return \Illuminate\Http\Response
     */
    public function edit(GrupaRobe $grupaRobe)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\GrupaRobe  $grupaRobe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, GrupaRobe $grupaRobe)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\GrupaRobe  $grupaRobe
     * @return \Illuminate\Http\Response
     */
    public function destroy(GrupaRobe $grupaRobe)
    {
        //
    }
}

resources/views/grupa_robe/create.blade.php
@extends('layouts.master')
@section('title', __('Nova grupa robe'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Nova grupa robe') }}</h3>

            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('Nova grupa robe') }}</h5>
                                    <form action="{{ route('grupa-robe.store') }}" method="POST">
                                        @csrf
                                        <div class="form-group row">
                                            <label for="naziv-input" class="col-sm-3 form-control-label">{{ __('Naziv') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="naziv"
                                                    class="form-control {{ $errors->has('naziv') ? 'is-invalid' : '' }}"
                                                    id="naziv-input"
                                                    placeholder="{{ __('Unesite naziv') }}"
                                                    value="{{ old('naziv') }}"
                                                >
                                                @if($errors->has('naziv'))
                                                    <small class="text-danger">{{ $errors->first('naziv') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="pdv-input" class="col-sm-3 form-control-label">
                                                {{ __('PDV') }}
                                            </label>
                                            <div class="col-sm-9">
                                                <select
                                                    name="pdv_id"
                                                    id="pdv-input"
                                                    class="form-control"
                                                >
                                                    <option disabled selected>Odaberite pdv</option>
                                                    @foreach($pdvs as $pdv)
                                                        <option value="{{ $pdv->id }}">{{ $pdv->naziv . ', ' . $pdv->aktivnaStopa->procenat . ' %' }}</option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('pdv_id'))
                                                    <small class="text-danger">{{ $errors->first('pdv_id') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <button class="float-right btn btn-primary">{{ __('Submit') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="text/javascript">
$(document).ready(function() {

});
</script>
@endsection

resources/views/grupa_robe/index.blade.php
@extends('layouts.master')
@section('title', __('Grupa robe'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Grupa robe') }}</h3>
            
            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-body-wrap-container">
                <div class="ks-full-table">
                    <div class="ks-full-table-header">
                        <h4 class="ks-full-table-name">{{ __('Grupa robe')}}</h4>
                        {{-- <div class="ks-controls">
                            <a href="{{ route('grupa-robe.create') }}">
                                <button class="btn btn-primary">{{ __('Napravite novu grupu')}}</button>
                            </a>
                        </div> --}}
                    </div>
                    <table id="grupa-robe-table" class="table ks-table-info dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th width="1">ID </th>
                                <th>{{ __('Naziv') }}</th>
                                <th>{{ __('PDV') }}</th>
                                <th>{{ __('Stopa PDV-a') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('external-js')
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/select2/js/select2.min.js') }}"></script>
<script type="application/javascript">var DatatablesDataSourceAjaxServer = {
    init: function () {
        $("#grupa-robe-table").DataTable({
            responsive: true, 
            searchDelay: 500, 
            processing: true, 
            serverSide: true, 
            ajax:"/grupa-robe", 
            columns: [
                { data: "id" }, 
                { data: "naziv" },
                { data: "pdv.naziv" },
                { data: "pdv.aktivna_stopa.procenat" }
            ]
        })
    }
};

jQuery(document).ready(function () {
    DatatablesDataSourceAjaxServer.init();

    $('body').delegate('.delete-group', 'click', function (e) {
        e.preventDefault();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var id = $(this).data('id');
        var name = $(this).data('name');
        var table = $("#groups-table").DataTable();
        var tr = $(this).parents('tr');

        $.confirm({
            title: 'Pažnja!',
            content: 'Da li želite da obrišete ' + name + '?',
            type: 'danger',
            buttons: {
                confirm: {
                    text: 'OK',
                    btnClass: 'btn-danger',
                    action: function () {
                        $.ajax({
                            url: '/otpremnice/' + id,
                            type: 'DELETE',
                        })
                        .done(function(data) {
                            table.row(tr).remove().draw();
                            ajaxNotify(data);
                        })
                        .fail(function() {
                            alert('Dogodila se greška');
                        });
                    }
                },
                cancel: function () {

                }
            }
        });
    });
});

</script>
@endsection