routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/getting-started', 'HomeController@start');
Route::post('/start', 'HomeController@starting');

Auth::routes();

Route::resource('narudžbenice', 'NarudzbenicaController')->middleware('auth');
Route::resource('fakture', 'FakturaController')->middleware('auth');
Route::resource('otpremnice', 'OtpremnicaController')->middleware('auth');
Route::resource('roba', 'RobaController')->middleware('auth');
Route::resource('grupa-robe', 'GrupaRobeController')->middleware('auth');
Route::resource('pdv', 'PdvController')->middleware('auth');
Route::resource('cenovnici', 'CenovnikController')->middleware('auth');
Route::put('cenovnici/aktivan/{cenovnik}', 'CenovnikController@toggleActive')->middleware('auth')->name('cenovnici.active');

Route::get('faktura/download/{faktura}', 'FakturaController@download')->name('faktura.download');

resources/views/cenovnici/create.blade.php
@extends('layouts.master')
@section('title', __('Novi cenovnik'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Kopirate cenovnik: ') . $stari_cenovnik->naziv }}</h3>

            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('Novi cenovnik') }}</h5>
                                    <form action="{{ route('cenovnici.store') }}" method="POST">
                                        @csrf
                                        <div class="form-group row">
                                            <label for="aktivan-input" class="col-sm-3 form-control-label">{{ __('Aktivan') }}</label>
                                            <div class="col-sm-9">
                                                <label class="ks-checkbox-slider ks-on-off ks-solid ks-primary">
                                                    <input
                                                        type="checkbox"
                                                        name="aktivan"
                                                        id="aktivan-input"
                                                        value="1"
                                                    >
                                                    <span class="ks-indicator"></span>
                                                    <span class="ks-on">Da</span>
                                                    <span class="ks-off">Ne</span>
                                            </label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="naziv-input" class="col-sm-3 form-control-label">{{ __('Naziv') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="naziv"
                                                    class="form-control {{ $errors->has('naziv') ? 'is-invalid' : '' }}"
                                                    id="naziv-input"
                                                    placeholder="{{ __('Unesite naziv') }}"
                                                    value="{{ old('naziv') }}"
                                                >
                                                @if($errors->has('naziv'))
                                                    <small class="text-danger">{{ $errors->first('naziv') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        {{-- <div class="form-group row">
                                            <label for="vazi-do-input" class="col-sm-3 form-control-label">{{ __('Važi do') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="datetime-local"
                                                    min="2019-01-01T00:00" 
                                                    max="2030-01-14T00:00"
                                                    step="1"
                                                    name="vazi_do"
                                                    class="form-control {{ $errors->has('vazi_do') ? 'is-invalid' : '' }}"
                                                    id="vazi-do-input"
                                                    placeholder="{{ __('Unesite datum važenja') }}"
                                                    value="{{ old('vazi_do') }}"
                                                >
                                                @if($errors->has('vazi_do'))
                                                    <small class="text-danger">{{ $errors->first('vazi_do') }}</small>
                                                @endif
                                            </div>
                                        </div> --}}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 ks-panels-column-section">
                            <div class="card">
                                <div class="ks-body-wrap-container">
                                    <div class="ks-full-table">
                                        <div class="ks-full-table-header">
                                            <h4 class="ks-full-table-name">
                                                {{ __('Roba cenovnika: ') . $stari_cenovnik->naziv }}
                                            </h4>
                                        </div>
                                        <table id="roba-table" class="table ks-table-info dt-responsive nowrap">
                                            <thead>
                                                <tr>
                                                    <th width="1">ID </th>
                                                    <th>{{ __('Naziv') }}</th>
                                                    <th>{{ __('$ Stara cena') }}</th>
                                                    <th>{{ __('$ Nova cena') }}</th>
                                                    <th>{{ __('Jedinica mere') }}</th>
                                                    <th>{{ __('Grupa robe') }}</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-4">
                                <div class="col-lg-12">
                                    <button id="cenovnik-submit" class="btn btn-primary">
                                        {{ __('Napravite cenovnik') }}
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/select2/js/select2.min.js') }}"></script>
<script type="application/javascript">
var DatatablesDataSourceAjaxServer = {
    init: function () {
        $("#roba-table").DataTable({
            responsive: true, 
            searchDelay: 500, 
            processing: true, 
            serverSide: true, 
            ajax:"{{ route('cenovnici.show', $stari_cenovnik) }}", 
            columns: [
                { data: "id" }, 
                { data: "naziv" },
                { 
                    data: "cenovnici",
                    render: function (data) {
                        return data[0].pivot.cena;
                    }
                },
                { 
                    data: "cenovnici",
                    render: function (data, type, row, meta) {
                        return '<input class="cenovnik-roba form-control col-lg-4" type="number" data-id="' + row.id + '" step="0.05" value="' + row.cenovnici[0].pivot.cena + '">';
                    }
                },
                { data: "jedinica_mere" },
                { data: "grupa_robe.naziv" },
            ]
        })
    }
};

$(document).ready(function () {
    DatatablesDataSourceAjaxServer.init();

    $('#cenovnik-submit').on('click', function (e) {
        e.preventDefault();

        var roba = [];
        $('.cenovnik-roba').each(function (i, obj) {
            let id = $(obj).data('id');
            let cena = obj.value;

            let stavka = {
                id: id,
                cena: cena
            };

            roba.push(stavka);
        });

        var aktivan = 0;
        if ($('#aktivan-input').is(':checked')) {
            aktivan = 1;
        }
        
        var naziv = $('#naziv-input').val();

        var data = {
            aktivan: aktivan,
            naziv: naziv,
            roba: roba
        };

        $.ajax({
            url: '{{ route('cenovnici.store') }}',
            type: 'POST',
            data: data,
            success: function (data) {
                let url = '{{ route('cenovnici.index') }}';
                window.location.replace(url);
            },
            error: function (data) {
                alert('error');
            }
        });
    });
});
</script>
@endsection

resources/views/cenovnici/datatable-action.blade.php
<div class="ks-controls">
    <a href="{{ route('cenovnici.show', $cenovnik) }}">
        <button type="button" class="btn btn-primary ks-light ks-no-text" style="line-height: 38px;">
            <span class="la la-eye ks-icon"></span>
        </button>
    </a>
    <a href="{{ route('cenovnici.edit', $cenovnik) }}">
        <button type="button" class="btn btn-success ks-light ks-no-text" style="line-height: 38px;">
            <span class="la la-copy ks-icon"></span>
        </button>
    </a>
    @if($cenovnik->aktivan)
        <button type="button" class="toggle-active btn btn-outline-primary ks-light ks-no-text" data-id="{{ $cenovnik->id }}" data-active="true" style="line-height: 38px;">
            <span class="la la-toggle-on ks-icon"></span>
        </button>
    @else
        <button type="button" class="toggle-active btn btn-outline-danger ks-light ks-no-text" data-id="{{ $cenovnik->id }}" data-active="false" style="line-height: 38px;">
            <span class="la la-toggle-off ks-icon"></span>
        </button>
    @endif
</div>

resources/views/cenovnici/edit.blade.php
@extends('layouts.master')
@section('title', __('Roba'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Roba') }}</h3>
            
            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-body-wrap-container">
                <div class="ks-full-table">
                    <div class="ks-full-table-header">
                        <h4 class="ks-full-table-name">{{ __('Sva roba cenovnika ') . $cenovnik->naziv }}</h4>
                    </div>
                    <table id="roba-table" class="table ks-table-info dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th width="1">ID </th>
                                <th>{{ __('Naziv') }}</th>
                                <th>{{ __('$ Cena') }}</th>
                                <th>{{ __('Jedinica mere') }}</th>
                                <th>{{ __('Grupa robe') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('external-js')
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/select2/js/select2.min.js') }}"></script>
<script type="application/javascript">var DatatablesDataSourceAjaxServer = {
    init: function () {
        $("#roba-table").DataTable({
            responsive: true, 
            searchDelay: 500, 
            processing: true, 
            serverSide: true, 
            ajax:"{{ route('cenovnici.show', $cenovnik) }}", 
            columns: [
                { data: "id" }, 
                { data: "naziv" },
                { 
                    data: "cenovnici" ,
                    render: function (data) {
                        return data[0].pivot.cena;
                    }
                },
                { data: "jedinica_mere" },
                { data: "grupa_robe.naziv" },
            ]
        })
    }
};

jQuery(document).ready(function () {
    DatatablesDataSourceAjaxServer.init();
});

</script>
@endsection

resources/views/cenovnici/index.blade.php
@extends('layouts.master')
@section('title', __('Cenovnici'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Cenovnici') }}</h3>
            
            <div class="ks-controls">

                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-body-wrap-container">
                <div class="ks-full-table">
                    <div class="ks-full-table-header">
                        <h4 class="ks-full-table-name">{{ __('Svi cenovnici')}}</h4>
                    </div>
                    <table id="cenovnici-table" class="table ks-table-info dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th width="1">ID </th>
                                <th>{{ __('Naziv') }}</th>
                                <th>{{ __('Aktivan') }}</th>
                                <th>{{ __('Napravljen') }}</th>
                                <th>{{ __('Akcija') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('external-js')
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/select2/js/select2.min.js') }}"></script>
<script type="application/javascript">var DatatablesDataSourceAjaxServer = {
    init: function () {
        $("#cenovnici-table").DataTable({
            responsive: true, 
            searchDelay: 500, 
            processing: true, 
            serverSide: true, 
            ajax:"/cenovnici", 
            columns: [
                { data: "id" }, 
                { data: "naziv" },
                { 
                    data: "aktivan",
                    render: function (data, type, row, meta) {
                        if (data == '1') {
                            return 'Da';
                        }

                        return 'Ne';
                    }
                },
                { data: "created_at" },
                { data: "action" }
            ]
        })
    }
};

$(document).ready(function () {
    DatatablesDataSourceAjaxServer.init();

    $('body').delegate('.toggle-active', 'click', function (e) {
        e.preventDefault();

        var id = $(this).data('id');
        var aktivan = $(this).data('active');

        if (aktivan) {
            alert('Izaberite neaktivan cenovnik');
            return;
        }

        var data = {
            id: id,
            aktivan: aktivan
        };

        $.ajax({
            url: '/cenovnici/aktivan/' + id,
            type: 'PUT',
            data: data,
            success: function (data) {
                alert('Uspeh');
            },
            error: function (data) {
                alert('Dogodila se greska');
            }
        });
    });

    // $('body').delegate('.delete-group', 'click', function (e) {
    //     e.preventDefault();

    //     $.ajaxSetup({
    //         headers: {
    //             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    //         }
    //     });

    //     var id = $(this).data('id');
    //     var name = $(this).data('name');
    //     var table = $("#groups-table").DataTable();
    //     var tr = $(this).parents('tr');

    //     $.confirm({
    //         title: 'Pažnja!',
    //         content: 'Da li želite da obrišete ' + name + '?',
    //         type: 'danger',
    //         buttons: {
    //             confirm: {
    //                 text: 'OK',
    //                 btnClass: 'btn-danger',
    //                 action: function () {
    //                     $.ajax({
    //                         url: '/cenovnici/' + id,
    //                         type: 'DELETE',
    //                     })
    //                     .done(function(data) {
    //                         table.row(tr).remove().draw();
    //                         ajaxNotify(data);
    //                     })
    //                     .fail(function() {
    //                         alert('Dogodila se greška');
    //                     });
    //                 }
    //             },
    //             cancel: function () {

    //             }
    //         }
    //     });
    // });
});

</script>
@endsection

resources/views/cenovnici/roba-datatable-action.blade.php
<button type="button" class="btn btn-primary ks-light ks-no-text" style="line-height: 38px;" data-id={{ $roba->id }}>
    <span class="la la-pencil ks-icon"></span>
</button>