routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/getting-started', 'HomeController@start');
Route::post('/start', 'HomeController@starting');

Auth::routes();

Route::resource('narudžbenice', 'NarudzbenicaController')->middleware('auth');
Route::resource('fakture', 'FakturaController')->middleware('auth');
Route::resource('otpremnice', 'OtpremnicaController')->middleware('auth');
Route::resource('roba', 'RobaController')->middleware('auth');
Route::resource('grupa-robe', 'GrupaRobeController')->middleware('auth');
Route::resource('pdv', 'PdvController')->middleware('auth');
Route::resource('cenovnici', 'CenovnikController')->middleware('auth');
Route::put('cenovnici/aktivan/{cenovnik}', 'CenovnikController@toggleActive')->middleware('auth')->name('cenovnici.active');

Route::get('faktura/download/{faktura}', 'FakturaController@download')->name('faktura.download');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/breadcrumbs.blade.php
<nav class="breadcrumb ks-default">
	@foreach ($breadcrumbs as $breadcrumb)	
	@if($breadcrumb->url && $breadcrumb->title == 'Home')
    <a class="breadcrumb-item ks-breadcrumb-icon" href="{{ $breadcrumb->url }}">
        <span class="la la-home ks-icon"></span>
    </a>
    @elseif($breadcrumb->url)
    <a href="{{ $breadcrumb->url }}" class="breadcrumb-item">{{ $breadcrumb->title }}</a>
    @elseif($breadcrumb->url && $loop->last)
    <span class="breadcrumb-item active" href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</span>
    @endif
    @endforeach
</nav>

resources/views/layouts/header.blade.php
    <!-- BEGIN HEADER -->
<nav class="navbar ks-navbar">
    <!-- BEGIN HEADER INNER -->
    <!-- BEGIN LOGO -->
    <div href="index.html" class="navbar-brand">
        <!-- BEGIN RESPONSIVE SIDEBAR TOGGLER -->
        <a href="#" class="ks-sidebar-toggle"><i class="ks-icon la la-bars" aria-hidden="true"></i></a>
        <a href="#" class="ks-sidebar-mobile-toggle"><i class="ks-icon la la-bars" aria-hidden="true"></i></a>
        <!-- END RESPONSIVE SIDEBAR TOGGLER -->

        <div class="ks-navbar-logo">
            <a href="{{ url('/')}} " class="ks-logo">Poslovna informatika</a>
        </div>
    </div>
    <!-- END LOGO -->

    <!-- BEGIN MENUS -->
    <div class="ks-wrapper">
        <nav class="nav navbar-nav">
            <!-- BEGIN NAVBAR MENU -->
            <div class="ks-navbar-menu">
            </div>
            <!-- END NAVBAR MENU -->

            <!-- BEGIN NAVBAR ACTIONS -->
            <div class="ks-navbar-actions">
                <!-- BEGIN NAVBAR ACTION BUTTON -->
                <!--
                <div class="nav-item nav-link btn-action-block">
                    <a class="btn btn-danger" href="#">
                        <span class="ks-action">Activate Your Account</span>
                        <span class="ks-description">trial ends in 1 day</span>
                    </a>
                </div>
            -->
                <!-- END NAVBAR ACTION BUTTON -->

                <!-- BEGIN NAVBAR USER -->
                <div class="nav-item dropdown ks-user">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="ks-avatar">
                            <img src="{{ asset('theme/lc-admin/assets/img/avatars/avatar-13.jpg') }}" width="36" height="36">
                        </span>
                        <span class="ks-info">
                            <span class="ks-name">{{ Auth::user()->ime . ' ' . Auth::user()->prezime }}</span>
                            <span class="ks-description">
                                {{ \App\Preduzece::find(session()->get('preduzece_id'))->naziv ?? 0 }}
                                |
                                {{ \App\PoslovnaGodina::find(session()->get('poslovna_godina_id'))->godina ?? 0 }}
                            </span>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Preview">
                        <a class="dropdown-item" href="{{ url('getting-started') }}">
                            <span class="la la-bars ks-icon" aria-hidden="true"></span>
                            Početni meni
                        </a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <span class="la la-sign-out ks-icon" aria-hidden="true"></span>
                            <span>{{__('Logout')}}</span>
                            <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;"> @csrf </form>
                        </a>
                    </div>
                </div>
                <!-- END NAVBAR USER -->
            </div>
            <!-- END NAVBAR ACTIONS -->
        </nav>

        <!-- BEGIN NAVBAR ACTIONS TOGGLER -->
        <nav class="nav navbar-nav ks-navbar-actions-toggle">
            <a class="nav-item nav-link" href="#">
                <span class="la la-ellipsis-h ks-icon ks-open"></span>
                <span class="la la-close ks-icon ks-close"></span>
            </a>
        </nav>
        <!-- END NAVBAR ACTIONS TOGGLER -->

        <!-- BEGIN NAVBAR MENU TOGGLER -->
        <nav class="nav navbar-nav ks-navbar-menu-toggle">
            <a class="nav-item nav-link" href="#">
                <span class="la la-th ks-icon ks-open"></span>
                <span class="la la-close ks-icon ks-close"></span>
            </a>
        </nav>
        <!-- END NAVBAR MENU TOGGLER -->
    </div>
    <!-- END MENUS -->
    <!-- END HEADER INNER -->
</nav>
<!-- END HEADER -->

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- BEGIN HEAD -->
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield ('title', 'Administration') | Poslovna Informatika</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @yield('external-meta')
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/fonts/line-awesome/css/line-awesome.min.css') }}">
    <!--<link rel="stylesheet" type="text/css" href="assets/fonts/open-sans/styles.css">-->

    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/fonts/montserrat/styles.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/tether/css/tether.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/jscrollpane/jquery.jscrollpane.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/flag-icon-css/css/flag-icon.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/common.min.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/lc-admin/assets/select2.min.css') }}" type="text/css" media="all">
    <link rel="stylesheet" href="{{ asset('theme/lc-admin/libs/jquery-confirm/jquery-confirm.min.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/lc-admin/libs/flatpickr/flatpickr.min.css') }}">
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/themes/primary.min.css') }}">
    {{-- <link class="ks-sidebar-dark-style" rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/themes/sidebar-black.min.css') }}"> --}}
    <link rel="stylesheet" href="{{ asset('theme/lc-admin/libs/notify/bootstrap-notify.min.css') }}">
    <!-- END THEME STYLES -->
    @yield('external-css')
</head>
<!-- END HEAD -->

<body class="ks-navbar-fixed ks-sidebar-default ks-sidebar-position-fixed ks-page-header-fixed ks-theme-primary ks-page-loading"> <!-- remove ks-page-header-fixed to unfix header -->

@include('layouts.header')






<div class="ks-page-container">

@include('layouts.sidebar')

@yield('content')
</div>

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ asset('theme/lc-admin/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/popper/popper.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/responsejs/response.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/loading-overlay/loadingoverlay.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/tether/js/tether.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/jscrollpane/jquery.jscrollpane.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/jscrollpane/jquery.mousewheel.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/flexibility/flexibility.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/velocity/velocity.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/jquery-confirm/jquery-confirm.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/notify/bootstrap-notify.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/flatpickr/flatpickr.min.js') }}"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="{{ asset('theme/lc-admin/assets/scripts/common.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('theme/lc-admin/assets/scripts/select2.full.min.js') }}"></script>
<!-- END THEME LAYOUT SCRIPTS -->

<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });
</script>

@yield('external-js')

<div class="ks-mobile-overlay"></div>

<!-- BEGIN SETTINGS BLOCK -->
<div class="ks-settings-slide-block">
    <a class="ks-settings-slide-control">
        <span class="ks-icon la la-cog"></span>
    </a>

    <div class="ks-header">
        <span class="ks-text">Layout Options</span>
        <a class="ks-settings-slide-close-control">
            <span class="ks-icon la la-close"></span>
        </a>
    </div>

    <ul class="ks-settings-list">
        <li>
            <span class="ks-text">Collapsed Sidebar</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-sidebar-checkbox-toggle">
                <input type="checkbox" value="1">
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
        <li>
            <span class="ks-text">Fixed page header</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-page-header-checkbox-toggle">
                <input type="checkbox" value="0" checked>
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
        <li>
            <span class="ks-text">Dark/Light Sidebar</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-sidebar-style-checkbox-toggle">
                <input type="checkbox" value="0" checked>
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
        <li>
            <span class="ks-text">White/Gray Content Background</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-content-bg-checkbox-toggle">
                <input type="checkbox" value="0" checked>
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
    </ul>
</div>
<!-- END SETTINGS BLOCK -->
</body>
</html>

resources/views/layouts/sidebar.blade.php
    <!-- BEGIN DEFAULT SIDEBAR -->
<div class="ks-column ks-sidebar ks-info">
    <div class="ks-wrapper ks-sidebar-wrapper">
        <ul class="nav nav-pills nav-stacked">

            <li class="nav-item">
                <a class="nav-link"  href="{{ url('/') }}" >
                    <span class="ks-icon la la-dashboard"></span>
                    <span>{{ __('Početna') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('narudžbenice.index') }}">
                    <span class="ks-icon la la-folder-open"></span>
                    <span>{{ __('Narudžbenice') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('fakture.index') }}">
                    <span class="ks-icon la la-file-o"></span>
                    <span>{{ __('Fakture') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('otpremnice.index') }}">
                    <span class="ks-icon la la-file-text-o"></span>
                    <span>{{ __('Otpremnice') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('roba.index') }}">
                    <span class="ks-icon la la-industry"></span>
                    <span>{{ __('Roba') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('grupa-robe.index') }}">
                    <span class="ks-icon la la-archive"></span>
                    <span>{{ __('Grupa robe') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('pdv.index') }}">
                    <span class="ks-icon la la-bank"></span>
                    <span>{{ __('PDV') }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('cenovnici.index') }}">
                    <span class="ks-icon la la-money"></span>
                    <span>{{ __('Cenovnici') }}</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- END DEFAULT SIDEBAR -->